### ISSUE TITLE
Tasks for revising the manuscript

### ISSUE THREAD

**Issue by Kamran-Khan96** [stemangiola/cellsig#78]
**Tasks to do:**

- [ ] Do the deconvolution benchmark with data modelled by glmmseq (https://cran.r-project.org/web/packages/glmmSeq/vignettes/glmmSeq.html) - implemented in tidybulk. Also, think about how to extend the results from figure 4.
- [ ] Update Github README with a readable vignette +  Organize the Github repo and provide installation directions
- [ ] Add a method/info section into the Shiny App + Shiny app should state the full HBCC acronym + Rshiny enable the high-resolution download of the plots
- [ ] Update the figures resolution and issues
- [ ] Write the response letter
- [ ] Update the manuscript
